services:
    backend:
        build:
            context: .
        ports:
            - 8080:3000
            - 9229:9229
        env_file: ./.env
        volumes:
            - ./:/usr/app
            - /usr/app/node_modules
        command: bash -c "npm run migrations && npm run watch"
        networks:
            - postgres
        depends_on:
            - db

    db:
        image: postgres
        env_file: ./.env
        volumes:
            - postgres:/data/postgres
        ports:
            - "5432:5432"
        networks:
            - postgres

networks:
    postgres:
        driver: bridge

volumes:
    postgres:
